### My http file
### Service document
http://localhost:51112/odata/v4/CatalogService/

###
http://localhost:51112/odata/v4/CatalogService/$metadata

### Get all POs
http://localhost:51112/odata/v4/CatalogService/POs

### Get single PO by ID
http://localhost:51112/odata/v4/CatalogService/POs('74867AD200E41EDBA5D8B0C98DC28052')

### Get POs with Pagination
http://localhost:51112/odata/v4/CatalogService/POs?$top=10&$skip=10

### Get filtered data ( with condition -> just like where in SQL )
http://localhost:51112/odata/v4/CatalogService/EmployeeSet?$filter=sex eq 'M'

### Filter with contains
http://localhost:51112/odata/v4/CatalogService/EmployeeSet?$filter=